---
# Script will install latest stable version of Java to enforce best practise.
- name: Install all required components for the JavaVM.
  hosts: all
  tasks:
    - name: Prints User's Linux Distribution.
      debug: msg=Distro:{{ ansible_distribution }}
    - name: Installs the JavaVM and other required packages. CENTOS
      yum: name={{ java_yum_packages }} state=latest
      become: true
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" or ansible_distribution == "RedHat"
    - name: Installs the JavaVM and other required packages. DEBIAN
      apt: name={{ java_apt_packages }} state=latest update_cache=yes
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Discovers the Installation Path for the JavaVM.
      command: "which java"
      register: java_home
    - name: Set the JAVA_HOME env variable. CENTOS
      lineinfile: path=/etc/environment line="export JAVA_HOME={{ java_home.stdout }}"
      become: true
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" or ansible_distribution == "RedHat"
    - name: Set the JAVA_HOME env variable. DEBIAN
      lineinfile: path=/etc/environment line="JAVA_HOME={{ java_home.stdout }}"
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  vars:
    java_yum_packages:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    java_apt_packages:
    - default-jre
    - default-jdk
