---
# Script will only install PHP7.x due to known security issues with PHP5.x
# Installation process uses Remi (https://rpms.remirepo.net/enterprise/7/)
# and Ondrej (ppa:ondrej/php) to access latest PHP packages.
- name: Install all required components for PHP.
  hosts: all
  tasks:
    - name: Prints User's Linux Distribution.
      debug: msg=Distro:{{ ansible_distribution }}
    - name: Installs the required Remi Repo packages. CENTOS
      yum: name={{ remi_packages }} state=latest
      become: true
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
    - name: Installs the latest PHP7.x package (current PHP7.3). CENTOS
      yum: name={{ php_yum_packages }} state=latest enablerepo=remi-php73
      become: true
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
    - name: Enables PHP packages on Amazon Machine by default. AMAZON.
      command: "amazon-linux-extras enable php7.3"
      become: true
      when: ansible_distribution == "Amazon"
    - name: Installs recommend PHP Modules. AMAZON
      yum: name={{ php_yum_packages }} state=latest
      become: true
      when: ansible_distribution == "Amazon"
    - name: Installs the required Ondrej PHP Repo packages. DEBAIN
      apt: name={{ ondrej_package }} state=latest
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Enables the Ondrej PHP Repo. DEBIAN
      apt_repository: repo=ppa:ondrej/php
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Install latest PHP7.x packages. DEBIAN
      apt: name={{ php_apt_packages }} state=latest
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  vars:
    remi_packages:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    php_yum_packages:
    - php
    - php-common
    - php-pear
    - php-opcache
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd
    - php-ldap
    - php-zip
    - php-fileinfo
    ondrej_package: software-properties-common
    php_apt_packages:
    - php7.3
    - php7.3-common
    - php-pear
    - php7.3-opcache
    - php7.3-cli
    - php7.3-gd
    - php7.3-curl
    - php7.3-mysql
    - php7.3-ldap
    - php7.3-zip
    - php7.3-fileinfo
