---
- name: Installs required Python components.
  hosts: all
  tasks:
    - name: Prints User's Linux Distribution.
      debug: msg=Distro:{{ ansible_distribution }}
    - name: Installs latest Python interpreter packages. CENTOS
      yum: name="{{ python_packages }}" state=latest
      become: true
      when: ansible_distribution == "CentOS" and ansible_distribution == "Amazon"
    - name: Installs latest Python interpreter packages. DEBIAN
      apt: name="{{ python_packages }}" state=latest
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Installs recomended Pip Packages.
      pip: name="{{ pip_packages }}" executable=pip3
      become: true
  vars:
    python_packages:
    - python3
    - python3-devel
    - python3-setuptools
    - python3-pip
    - python3-tkinter # GUI Library
    pip_packages:
    - requests #HTTP Requests Library
    - scrapy # Web-Scrapping Library
    - tensorflow # Machine Learning Library
    - scapy # Packet Sniffing Library
    - pendulum # Date/Time Parsing Library
    - dash # Web Application Build Library
    - nltk # NLP Library
