---
- name: Install the latest Ruby version and RVM.
  hosts: all
  tasks:
    - name: Prints User's Linux Distribution.
      debug: msg=Distro:{{ ansible_distribution }}
    - name: Enable Ruby on Amazon systems. AMAZON
      command: "amazon-linux-extras enable ruby2.4"
      become: true
      when: ansible_distribution == "Amazon"
    - name: Installs Ruby and dependancies. CENTOS
      yum: name={{ ruby_yum_packages }} state=latest
      become: true
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon"
    - name: Installs Ruby and dependancies. DEBIAN
      apt: name={{ ruby_apt_packages }} state=latest update_cache=yes
      become: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Configures Keys to Obtain RVM Package (1/2). ALL
      shell: "curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -"
      become: true
    - name: Configures Keys to Obtain RVM Package (2/2). ALL
      shell: "curl -sSL https://get.rvm.io | bash -s stable"
      become: true
    - name: Sources RVM Installation Script. ALL
      shell: cmd="source ~/.rvm/scripts/rvm"
      become: true
  vars:
    ruby_yum_packages:
    - ruby
    - gnupg # Key Management Tool.
    - ruby-irb
    - rubygem-rake # Ruby Build Automation Tool.
    - rubygem-json ~ JSON Parsing Gem.
    - rubygems # Gem Management Tool.
    - git-core
    - zlib
    - zlib-devel
    - gcc-c++
    - patch
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
    - sqlite-devel
    ruby_apt_packages:
    - ruby-full
    - gnupg2 # Key Management Tool
    - curl
    - g++
    - gcc
    - autoconf
    - automake
    - bison
    - libc6-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libsqlite3-dev
    - libtool
    - libyaml-dev
    - make
    - pkg-config
    - sqlite3
    - zlib1g-dev
    - libgmp-dev
    - libreadline-dev
    - libssl-dev
